"""Add RelationshipEditRequest model

Revision ID: 15f9782975f9
Revises: 37fa9a0c6397
Create Date: 2025-07-27 14:45:58.952465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f9782975f9'
down_revision = '37fa9a0c6397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_edit_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('current_relationship_type', sa.String(length=50), nullable=False),
    sa.Column('new_relationship_type', sa.String(length=50), nullable=False),
    sa.Column('field_to_change', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_edit_request')
    # ### end Alembic commands ###
