"""Add comprehensive profile fields and privacy settings

Revision ID: 16cd4a944967
Revises: c09dd9615b1d
Create Date: 2025-07-27 14:31:53.998216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cd4a944967'
down_revision = 'c09dd9615b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('job_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bio_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('location_private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location_private')
        batch_op.drop_column('bio_private')
        batch_op.drop_column('job_private')
        batch_op.drop_column('phone_private')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('job')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
