"""Add bidirectional relationship support

Revision ID: 37fa9a0c6397
Revises: 16cd4a944967
Create Date: 2025-07-27 14:44:25.401102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fa9a0c6397'
down_revision = '16cd4a944967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reverse_relationship_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_bidirectional', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_column('is_bidirectional')
        batch_op.drop_column('reverse_relationship_type')

    # ### end Alembic commands ###
